// src/app/common/components/not-found/not-found.component.ts
import { RouterModule } from '@angular/router'
import { Component, Input } from '@angular/core'
import * as Sentry from '@sentry/angular'

@Component({
  selector: 'spomen-not-found',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './not-found.component.html',
  styleUrl: './not-found.component.scss',
})
@Sentry.TraceClass({ name: 'NotFound' })
export class NotFoundComponent {
  @Input() title: string = 'Такой страницы не существует'
  @Input() showRef: boolean = true
}

<span class="not-found__title">{{ this.title }}</span>

@if (this.showRef) {
  <a routerLink="/" class="not-found__btn button"><span>На главную</span></a>
}

// components/elements/NotFound/index.tsx
import Button from '@elements/Button'

import { Component } from '@typs/components'

import './index.sass'

const NotFound: Component<{}> = () => {
  return (
    <div className='not-found'>
      <span className='not-found__title'>Такой страницы не существует</span>
      <Button className='not-found__button' type='a' to='/'>
        На главную
      </Button>
    </div>
  )
}

export default NotFound
