// src/app/not-found/not-found.component.ts
import { RouterModule } from '@angular/router'
import { Component } from '@angular/core'

@Component({
  selector: 'spomen-not-found',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './not-found.component.html',
  styleUrl: './not-found.component.scss',
})
export class NotFoundComponent {}

<span class="not-found__title">Такой страницы не существует</span>
<a routerLink="/" class="not-found__btn button">На главную</a>

// components/elements/NotFound/index.tsx
import Button from '@elements/Button'

import { Component } from '@typs/components'

import './index.sass'

const NotFound: Component<{}> = () => {
  return (
    <div className='not-found'>
      <span className='not-found__title'>Такой страницы не существует</span>
      <Button className='not-found__button' type='a' to='/'>
        На главную
      </Button>
    </div>
  )
}

export default NotFound
